### PR TITLE
replace argument sign '-' to '--' in "Windows Service Documentation.md"

### PR DESCRIPTION
**Pull request by Hawkeyes0**

### CODE REVIEW

**Comment by ghost** [comment]
Hi **@Hawkeyes0**, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by enricogior** [comment]
Hi @Hawkeyes0 
thank you very much for the PR.
The PR will be included in the next release on both the 2.8 and 3.0 branches.
Thanks!

**Comment by Hawkeyes0** [comment]
Thx.
I think this is a mistake. But my workmate crashed 2 days :laughing:

**Comment by enricogior** [comment]
@Hawkeyes0 
a good mistake :)

**Comment by enricogior** [comment]
Closing the PR since it has been merged on both the 2.8 and 3.0 branches.
Thank you.

**Pull request closed without merging**
