### PR TITLE
Unable to build Redis 3.0 on 32 bit 

### PR DESCRIPTION
**Pull request by Jens-G**
... due to missing comma & misplaced semicolon

### CODE REVIEW

**Comment by ghost** [comment]
Hi **@Jens-G**, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by Jens-G** [comment]
The change in zmalloc.h fixes the issue:

```
  redis\src\zmalloc.h(91): error C2143: Syntaxfehler: Es fehlt ')' vor ';'
  redis\src\zmalloc.h(91): error C2059: Syntaxfehler: ')'
    zipmap.c
  redis\src\zmalloc.h(91): error C2143: Syntaxfehler: Es fehlt ')' vor ';'
  redis\src\zmalloc.h(91): error C2059: Syntaxfehler: ')'
    zmalloc.c
```

**Comment by ghost** [comment]
**@Jens-G**, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by enricogior** [comment]
Hi @Jens-G 
thanks again for the PR, we will merge the fixes for the jemalloc lib and for the missing comma.
The misplaced semicolon is actually not misplaced, the problem is with #ifdef WIN32 at the top of the file that should instead be #ifdef _WIN32.
There is no need to re-submit the PR, when I merge it I'll change the fix for the compiler error.
Thank you.

**Comment by Jens-G** [comment]
> The misplaced semicolon is actually not misplaced,

Ah, I see. I knew there was something strange about it. Makes sense. Thanks, and also thanks for all the great work with Redis!

**Comment by enricogior** [comment]
The PR has been merged in the 3.0.500-rc2 release.
Thank you!

**Pull request closed without merging**
