### PR TITLE
refresh cli prompt bug fix

### PR DESCRIPTION
**Pull request by openbaas**
after failing connect to server through redis-cli 

and try to redis server using "redis-server"

It couldn't update the redis-cli prompt 

before:

``` c
charsyam@ubuntu:~/projects/redis-charsyam/src$ redis-cli -p 3000
Could not connect to Redis at 127.0.0.1:3000: Connection refused
not connected> connect 127.0.0.1 6379
redis 127.0.0.1:3000> <-- it isn't updated.
```

applying this patch.

``` c
charsyam@ubuntu:~/projects/redis-charsyam/src$ ./redis-cli -p 3000
Could not connect to Redis at 127.0.0.1:3000: Connection refused
not connected> connect 127.0.0.1 6379
redis 127.0.0.1:6379>
```

It is updated well.

### CODE REVIEW

**Comment by clca** [comment]
Thanks a lot for your contribution. In order to accept your pull request I need you to sign a CLA as explained at https://github.com/MSOpenTech/redis/wiki/Contribute. By signing the CLA you will be able to contribute to the project at any time in the future.

**Comment by charsyam** [comment]
@clca, Could I scan it through my camera? I have no scanner. and this patch is also submitted real redis source. :)

**Comment by clca** [comment]
that's fine, I just need the content of the document to be readable. We will have a much better process based on eSign soon.

**Comment by jepickett** [comment]
2.6.14 and 2.8.4 have been released. The signed binaries are available through NuGet and Chocolatey. The problem does not reproduce in those versions.

**Pull request closed without merging**
