### PR TITLE
Port diskless replication to Windows

### PR DESCRIPTION
**Pull request by orangemocha**
See http://antirez.com/news/81 for background on diskless replication.

### CODE REVIEW

**Comment by jepickett** [comment]
My concern is that Windows pipes are implemented very differently from Unix pipes. On Windows pipes are implemented a network service. The benefit is that you can use a pipe across machine boundaries. This is how the IPC$ administrative share works for remote regedit, etc. On Unix a pipe is implemented as a piece of shared kernel memory with a very thin API layer over it. In my tests windows pipes are 10 times slower than using a socket, and orders of magnitude slower than using shared memory. It seems worth the extra performance to go with at least a socket based implementation. 

When AzureCache modified their implementation to implement diskless replication, they went with shared memory. I am hoping the performance of our implementation will be good enough to motivate the AzureCache team to accept our changes, rather than continue on with divergent forking code.It would be interesting to compare the performance of a localhost socket with  SIO_LOOPBACK_FAST_PATH relative to shared memory.

**Comment by orangemocha** [comment]
@jepickett pipes have a very marginal role in diskless replication. They are used for the forked child process to acknowledge back to the master which slaves were successfully synchronized. The bulk of diskless replication happens over sockets (and shared memory is not really an option there, because slaves don't necessarily run on the same machine as master). 

Here's a link to antirez blog describing the implementation of diskless replication: http://antirez.com/news/81 
Apologies for not posting that earlier.

**Comment by kirkshoop** [comment]
I agree with @jepickett that the Sockets should have SIO_LOOPBACK_FAST_PATH set.
I also did not see in the diff where the sockets that are created and duplicated were freed.

**Comment by orangemocha** [comment]
> Sockets should have SIO_LOOPBACK_FAST_PATH set.

This was set in the parent, and it's unnecessary to redo it for the duplicate descriptor. From https://msdn.microsoft.com/en-us/library/windows/desktop/ms741565%28v=vs.85%29.aspx: 
"All of the state information associated with a socket is held in common across all the descriptors because the socket descriptors are duplicated and not the actual socket."

> I also did not see in the diff where the sockets that are created and duplicated were freed.

They are not being freed explicitly, but the child process will exit immediately after the sync and the OS will close the child's duplicated descriptor. I could add an explicit closing, but the posix side is not closing them explicitly either.

**Pull request merged**
