### PR TITLE
 sentinel notification script - access violation exception

### PR DESCRIPTION
**Pull request by flavius-m**
Using a notification script when running Redis Server Win64  as a sentinel causes an "Access violation exception".  This can be fixed by passing  the STARTUPINFO parameter to CreateProcessA instead of NULL.  

Configuration example:
sentinel notification-script mymaster ConsoleApplication.exe
Exception:
Access violation reading location 0x0000000000000060.

### CODE REVIEW

**Comment by ghost** [comment]
Hi **@flavius-m**, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, MSOTBOT;

**Comment by flavius-m** [comment]
Could solve reported issues:
https://github.com/MSOpenTech/redis/issues/321
https://github.com/MSOpenTech/redis/issues/298

**Comment by flavius-m** [comment]
Made another change to use only the parameter lpCommandLine parameter for CreateProcessA and added NULL termination for the command line string.

This way arguments are correctly sent and you can use Batch files as notification scripts.

Please see - https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425%28v=vs.85%29.aspx

**Comment by enricogior** [comment]
Hi @flavius-m 
thank you very much for sending the PR, we will review it and it  will be included in the next release on both the 2.8 and 3.0 branches.

**Comment by enricogior** [comment]
Closing the PR since it has been merged on both 2.8 and 3.0 branches.
Thank you.

**Pull request closed without merging**
