### PR TITLE
Socket handling fixes

### PR DESCRIPTION
**Pull request by fammollo**
Handle socket connection errors (e.g. timeouts)
Use select instead of poll if not at least on Win8

### CODE REVIEW

**Comment by ghost** [comment]
Hi **@fammollo**, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by ghost** [comment]
**@fammollo**, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by enricogior** [comment]
Hi @fammollo ,
thanks for pointing out the bug and for the proposed fix.
It turned out that WSAPoll is also broken in Windows 8 and later, so we will fix this in a different way. Therefore we will not merge your PR, but thanks again for you contribution :)

**Comment by fammollo** [comment]
Hello Enrico,

the main goal of my patch was to be able to use select instead of poll and during the process I had to fix using select because it was broken too.

I only need hiredis from the client side perspective, so, since the client is interested about just one socket, there is no noticeable penalty in using select instead of poll
and the check about the Windows version I put there could be just commented out in order to always use select, or be enabled on Windows 10 if it works there.

From the server side perspective, I understand that using select instead of poll could have its limitations and that my PR cannot be considered generic.

Certainly, until you publish a different kind of fix, I’ll have to keep using mine. ;)

Best regards,
Fabrizio

Da: Enrico Giordani [mailto:notifications@github.com]
Inviato: giovedì 30 luglio 2015 17:03
A: MSOpenTech/redis
Cc: Fabrizio Ammollo
Oggetto: Re: [redis] Socket handling fixes (#273)

Hi @fammollohttps://github.com/fammollo ,
thanks for pointing out the bug and for the proposed fix.
It turned out that WSAPoll is also broken in Windows 8 and later, so we will fix this in a different way. Therefore we will not merge your PR, but thanks again for you contribution :)

—
Reply to this email directly or view it on GitHubhttps://github.com/MSOpenTech/redis/pull/273#issuecomment-126360709.

Informativa Privacy - Ai sensi del D. Lgs n. 196/2003 (Codice Privacy) precisiamo che le informazioni contenute in questo messaggio sono riservate e a uso esclusivo del destinatario. Ogni uso, copia o distribuzione non autorizzata è proibita e passibile di sanzioni ai termini di legge. Reitek non è responsabile di eventuali copie o distribuzioni non autorizzate. Se questo messaggio è stato ricevuto per errore, preghiamo gentilmente di eliminarlo e di informare il mittente. Grazie.

**Comment by enricogior** [comment]
@fammollo,
it will take a while before we will publish a fix because now we are focused on releasing v3.0, so I'm glad you can use your fix in the meanwhile.

**Pull request closed without merging**
