### PR TITLE
Added Windows Installers using WiX - x86 and x64

### PR DESCRIPTION
**Pull request by NickMRamirez**
- This change adds two new project to the msvs folder -- a WiX project that will build a Windows installer (.msi). This installer does the following:

Installs files to Program Files (x86)\Redis-Windows or Program Files\Redis-Windows
Installs Redis as a Windows service that runs under the NetworkService account
Adds program to "Programs and Features" for easy removal
Installer can be run from the command-line with the syntax: msiexec /i Redis-Windows-x64.msi LOGLEVEL=verbose CONFIG=redis.windows.conf
Installer can be run by double-clicking the built MSI
Defaults to loglevel "verbose" and config "redis.windows.conf"
Caveats

Currently, there is no GUI for the installer, but one could be added later

### CODE REVIEW

**Comment by NickMRamirez** [comment]
Not sure why candle.exe is failing on AppVeyor. If the file is there, it should run okay. I haven't used AppVeyor before. Anyone know more?

**Comment by baywet** [comment]
Are you planning to deliver the msi installers with the binary releases? So we don't have to build it ourselves.

**Comment by NickMRamirez** [comment]
I'm a bit new to github. Two blockers currently are: (1) this Appveyor builder seems to not like calling the candle.exe executable, which is the WiX compiler. I've included candle.exe in the source files, but maybe there's a security rule against it. It does build locally. (2) I'd like to add a rule to the installer to make an exception in the Windows firewall for redis. It's easy to do and I plan to do it soon.

I'm not sure how to add the MSIs to the binaries. I think it would be useful though! I'm just trying to install redis with Chef, since I'm learning Chef, and an MSI seemed like the better way to go.

Currently, I closed the pull request.

**Comment by baywet** [comment]
I'm not very familiar with Git neither. I actually didn't know until 20 minutes ago it was capable of automated build and release management.
We've included Redis to our software and we programmatically do the installation steps (copy binaries, declare as a service, add exception...) but it would be nice to have an MSI doing that.
We could build the whole project in our VS Online environment but I don't want to add the compilation of redis + MSI's to our build process that would slow it down a lot.
Anyway if you could add it to the release that'd be great, otherwise I guess i'll manually update it from time to time.

**Comment by NickMRamirez** [comment]
Okay,  might not be much to it.  I will try to find out.

**Pull request closed without merging**
